image: python:2.7.14

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -U pipenv
          - pip install -r requirements.txt
          - python manage.py migrate --noinput
          - python manage.py migrate --noinput
          - python manage.py makemigrations accounts
          - python manage.py makemigrations wallet
          - python manage.py makemigrations transactions
          - python manage.py makemigrations packages
          - python manage.py migrate
        services:
          - database
definitions:
  services:
    database:
      image: postgres:9.6.6-alpine
      environment: 
        avicrypto_db: "postgres"
        avicrypto_user: "postgres"
        avicrypto_pwd: "postgres"
        avicrypto_host: "localhost"