image: python:2.7.14

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -U pipenv
          - pip install -r requirements.txt
          - python manage.py migrate --noinput
          - python manage.py migrate --noinput
          - python manage.py makemigrations accounts
          - python manage.py makemigrations wallet
          - python manage.py makemigrations transactions
          - python manage.py makemigrations packages
          - python manage.py migrate
          - pw_dir=$(pwd)
          - cd .. && git clone git@github.com:codecakes/avi.github.io.git
          - cd avi.github.io.git && cp -R $pw_dir/staticfiles ./
          - echo $(git status)
          - git add * && git commit -am "updated staticfiles"
          - git push
        services:
          - database
definitions:
  services:
    database:
      image: postgres:9.6.6-alpine
      environment: 
        avicrypto_db: "postgres"
        avicrypto_user: "postgres"
        avicrypto_pwd: "postgres"
        avicrypto_host: "localhost"