# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('tx_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reciever_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.Wallet')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.Wallet')),
            ],
        ),
    ]
