# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=100, null=True)),
                ('package_code', models.CharField(blank=True, max_length=50, null=True)),
                ('payout', models.FloatField(blank=True, default=0.0, null=True)),
                ('directout', models.FloatField(blank=True, default=0.0, null=True)),
                ('binary_payout', models.FloatField(blank=True, default=0.0, null=True)),
                ('capping', models.FloatField(blank=True, default=0.0, null=True)),
                ('no_payout', models.FloatField(blank=True, default=0.0, null=True)),
                ('loyality', models.FloatField(blank=True, default=0.0, null=True)),
                ('roi', models.FloatField(blank=True, default=0.0, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('NA', 'Non-Active'), ('C', 'Confirmed'), ('NC', 'Non-Confirmed')], default='NA', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='packages.Packages')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
