# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_packages',
            name='last_payout_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 0, 0, tzinfo=utc)),
        ),
    ]
