# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_user_packages_last_payout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_packages',
            name='binary',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='user_packages',
            name='direct',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='user_packages',
            name='weekly',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
